version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: orders_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: KiS3k!w0rLd
    ports:
      - 27017:27017
    volumes:
      - ./data:/docker-entrypoint-initdb.d
